version: '3.3'

services:
    gophster.reverse-proxy:
        container_name: 'gophster.reverse-proxy'
        image: traefik:v1.7
        command: --api --docker
        labels:
            - traefik.frontend.rule=Host:monitor.gophster.localhost
            - traefik.port=8080
        ports:
            - '80:80'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    gophster.api:
        container_name: 'gophster.api'
        user: node
        image: node:13.8.0-stretch
        labels:
            - traefik.frontend.rule=Host:api.gophster.localhost
            - traefik.port=3000
        depends_on:
            - 'gophster.reverse-proxy'
        expose:
            - '3000'
        volumes:
            - './services/gophster-api:/home/node/app'
        working_dir: /home/node/app
        command: sh -c 'tail -f /dev/null'

    gophster.frontend:
        container_name: 'gophster.frontend'
        user: node
        image: node:13.8.0-stretch
        labels:
            - traefik.frontend.rule=Host:frontend.gophster.localhost
            - traefik.port=4200
        depends_on:
            - 'gophster.reverse-proxy'
        expose:
            - '4200'
        volumes:
            - './services/gophster-frontend:/home/node/app'
        working_dir: /home/node/app
        command: sh -c 'tail -f /dev/null'

    gophster.maindb:
        container_name: 'gophster.maindb'
        image: postgres:12.2-alpine
        env_file:
            - .env
        volumes:
            - maindb:/var/lib/postgresql/data

    gophster.redis:
        container_name: 'gophster.redis'
        image: 'redis'
        expose:
            - '6379'

volumes:
    maindb:
